version: "3.9"
services:
  db:
    image: postgres:16
    container_name: learnlab-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: learnlab
    ports:
      - "5432:5432"